### ISSUE TITLE
App crashes when launched

### ISSUE THREAD

**Issue by krotoxx** [nshetty26/MH4UDatabase#1]
So I have an iPod touch and it as iOS 6.1.6 and after downloading the app when I go to launch it the app auto crashes and doesn't pull up anything. No idea why this happens but maybe you can look into that

**Comment by nshetty26** [comment]
Yes this is a known issue. This should be fixed in the next release coming within the next week or two.

**Comment by khamptonkh** [comment]
Please fix this soon mr. Shetty.  I use the app on my wife's iphone 5 and LOVE IT.  I would love to be able to use it on my iphone 4.  Thank you sir.

**Comment by nshetty26** [comment]
The new release will fix this along with a slew of new features and should be available next week! It's been in review for 6 days now.

**Comment by nshetty26** [comment]
New release is now on the AppStore. You can now download it and use the app on iOS 7.1+
